Provide sync instructions
salesforcecli/plugin-apex pull request #152
Opened 2023-06-06 20:15 UTC by iowillhoit

### What does this PR do?
Now that tests run async by default, this provides instructions on how to wait for test results. Also updates help docs to reflect the change to async by default. 

I originally used some `oclif` flag relationships to enforce this suggestion, but a lot of these flags are tightly coupled and it caused other issues. I think this quick fix is sufficient for now.

Another semi-related change: For some reason, if you passed `--synchronous` and `--json` it would immediately return with the `testRunId`. That made no sense to me, so I changed it. Let me know if you can think of a reason that this was the case.

QA Suggestions
- Run with `sf apex test run`
  - Confirm `get` command is logged as well as sync suggestion
- Run with `sf apex test run --json`
  - Confirm the `testRunId` exist in json
  - Thought: We could push the "sync instructions" to the `warnings` array 🤷‍♂️
- Run `sf apex test run -w 1` 
  - Confirm results are printed to stdout
- Run `sf apex test run -w 1 --json` 
  - Confirm results are printed as `json` to stdout 
- Run `sf apex test run -y` 
  - Confirm results are printed to stdout
- Run `sf apex test run -y --json` 
  - Confirm results are printed as `json` to stdout
  - NOTE: This is the other change listed above, this used to immediately return.  

### What issues does this PR fix or reference?
https://github.com/forcedotcom/cli/issues/2162
[@W-13486954@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-13486954)

2023-06-06 20:38 UTC, jshackell-sfdc commented on messages/runtest.md
> +Apex tests run asynchronously by default and will immediately return a test run ID. Alternatively a minute duration can be passed to the --wait flag; if the tests finish in that timeframe, the comman
```suggestion
By default, Apex tests run asynchronously and immediately return a test run ID. You can use the --wait flag to specify the number of minutes to wait; if the tests finish in that timeframe, the command displays the results. If the tests haven't finished by the end of the wait time, the command displays a test run ID. Use the "<%= config.bin %> apex get test --test-run-id" command to get the results.
```

2023-06-06 20:39 UTC, jshackell-sfdc approved these changes
See my edit, but otherwise looks good!

2023-06-07 18:12 UTC, mshanemc approved these changes

2023-06-07 18:46 UTC, mshanemc commented
QA notes:

run and get a test
✅ shows the get command and the `--synchronous` suggestion
📓 I'm ok without more warnings in the json.

test with --wait 1 on 1 test (-t)
✅ shows test results 

test with --wait 1 with all tests
✅ shows test results  (tried to make it time out but that pesky Salesforce is just too fas!)

test with --wait 0 with all tests
✅ async, shows new message
✅ shows testrunId if --json

❓  `-w 0 -y` What should happen here?  Is it asynchronous or not?  Or should we throw a warning/error from `validateFlags` to help the user fix that conflict?  

-y --json
✅ good results to stdout.  


> That made no sense to me, so I changed it
about 500 executions/week use --json with --synchronous , out of the 2900/week that have --json on it.  About half of the coincidence is CI.

I agree that this is a better UX.  I think if you really want to change the json behavior, we should put a warning on that coincidence of flags, and give people the full 4 months to adjust.  ex:
- WARNING: using `--json` and `--synchronous` currently [describe current] .  After [date] we will change it to [new behavior]
- if you want to continue getting the `testRunId` in json, use [various ways to get that]
- if you want the new behavior now, you can [ -w --json ? ]

you could even put a date-based gate(s) on the behavior and a to-do to remove it later if you want.

2023-06-07 18:47 UTC, mshanemc requested changes
let's not break json for CI

2023-06-07 20:24 UTC, iowillhoit commented
> `-w 0 -y` What should happen here? Is it asynchronous or not? Or should we throw a warning/error from validateFlags to help the user fix that conflict?

I think that the current functionality is what I would expect since the default is async tests and `-w 0` is essentially the same. Passing `-y` would overwrite the default to run sync.

2023-06-07 20:26 UTC, mshanemc approved these changes

2023-06-07 20:37 UTC, merged