Wr/sf
salesforcecli/plugin-apex pull request #29
Opened 2023-01-31 17:04 UTC by WillieRuemmele

### What does this PR do?
base branch for sf-ifying

running on `SfCommand`

### What issues does this PR fix or reference?
@W-12083478@

2023-02-08 13:38 UTC, peternhale requested changes

2023-02-08 13:38 UTC, peternhale commented on src/commands/force/apex/test/run.ts
> +    loglevel: Flags.enum({
to Flags.string

2023-02-08 13:38 UTC, peternhale commented on src/commands/force/apex/test/run.ts
> +    outputdir: Flags.string({
to Flags.directory

2023-02-08 13:38 UTC, peternhale commented on src/commands/force/apex/test/run.ts
> +    testlevel: Flags.enum({
Flags.string

2023-02-08 13:38 UTC, peternhale commented on src/commands/force/apex/test/run.ts
> +    resultformat: Flags.enum({
Flags.string

2023-02-08 13:38 UTC, peternhale commented on src/commands/force/apex/test/run.ts
> +      // return null;
remove if not needed

2023-02-13 20:45 UTC, mshanemc approved these changes

2023-02-13 20:45 UTC, mshanemc commented on test/commands/force/apex/log/list.test.ts
> +      expect(ctx.stdout).to.include(
eww.  I think I'd rather assert that the correct args are passed to `this.table` instead of writing an integration test for cliUx

2023-02-14 17:12 UTC, peternhale approved these changes

2023-02-14 20:25 UTC, merged